### ISSUE TITLE
Error: run_example.sh: line 33: cx-trace: command not found

### ISSUE THREAD

**Issue by YiFeiSong-ict** [IBM/chopstix#54]
After running  the given tracing example shell,  Error "cx-trace: command not found" is reported. 
And I cannot find the cx-trace binary. I wonder to know if it has been transferred to "chop trace".
`
die() {
    echo "$@" >&2
    exit 1
}

rm -rf data
mkdir data

export TEST_ITER=10000
export TEST_SIZE=10000:w

cx-trace "$@" ./daxpy
`

**Comment by YiFeiSong-ict** [comment]
And, after I changing the **cx-trace** to **chop trace** a new **ERROR** occurs:
**_chopstix driver: error: Tracer:: track_mmap: Child did not stop_**
After some debug try, we find the final signal the waitpid received is 0, which we guess means the tracee process has been killed at that time.

**Comment by rbertran** [comment]
Please check the latest updated example and documentation.
